import { supabase, isConfigured, SUPABASE_URL, SUPABASE_ANON_KEY } from "./supabaseClient.js";
import { generateCode, showError, hideError } from "./util.js";
const Upload=window.tus?.Upload; if(!Upload) throw new Error("Nightcast upload client failed to load.");
const $=(id)=>document.getElementById(id); const errorBox=$("errorBox"),fileInput=$("fileInput"),dropzone=$("dropzone"),dzText=$("dzText"),fileNameEl=$("fileName"),roomNameInput=$("roomNameInput"),createBtn=$("createBtn"),progressWrap=$("progressWrap"),progressBar=$("progressBar"),codeInput=$("codeInput"),joinBtn=$("joinBtn"),roomsList=$("roomsList");
let selectedFile=null;
if(!isConfigured) showError(errorBox,"Nightcast is not connected to Supabase.");
function ownedRooms(){try{return JSON.parse(localStorage.getItem("nightcast_owned_rooms")||"[]")}catch{return[]}}
function saveOwnedRooms(r){localStorage.setItem("nightcast_owned_rooms",JSON.stringify(r.slice(-50)))}
function rememberRoom(code,ownerToken){saveOwnedRooms([...ownedRooms().filter(r=>r.code!==code),{code,ownerToken}])}
function forgetRoom(code){saveOwnedRooms(ownedRooms().filter(r=>r.code!==code))}
function selectFile(file){if(!file?.type?.startsWith("video")&&!file?.type?.startsWith("audio")){showError(errorBox,"Choose a video or audio file.");return}hideError(errorBox);selectedFile=file;dzText.innerHTML="<strong>File ready</strong><br/>click to choose another";fileNameEl.textContent=file.name;fileNameEl.style.display="block";createBtn.disabled=false}
fileInput.addEventListener("change",()=>selectFile(fileInput.files[0]));["dragover","dragenter"].forEach(e=>dropzone.addEventListener(e,ev=>{ev.preventDefault();dropzone.classList.add("drag")}));["dragleave","drop"].forEach(e=>dropzone.addEventListener(e,ev=>{ev.preventDefault();dropzone.classList.remove("drag")}));dropzone.addEventListener("drop",ev=>selectFile(ev.dataTransfer.files[0]));
createBtn.addEventListener("click",()=>{if(!selectedFile||!isConfigured)return;hideError(errorBox);createBtn.disabled=true;createBtn.textContent="Uploading… 0%";progressWrap.style.display="block";progressBar.style.width="0%";const code=generateCode(),ownerToken=crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");const roomName=roomNameInput.value.trim().slice(0,80)||"Nightcast Room";const ext=(selectedFile.name.split(".").pop()||"bin").toLowerCase(),path=`${code}.${ext}`;
// Supabase's documented TUS endpoint is the project URL's /storage/v1/upload/resumable route.
// Do not rewrite it to the *.storage.supabase.co host: that host can cause the upload
// request's signature to be rejected by the Storage gateway.
const upload=new Upload(selectedFile,{endpoint:`${SUPABASE_URL}/storage/v1/upload/resumable`,retryDelays:[0,3000,5000,10000,20000],chunkSize:6*1024*1024,uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,headers:{authorization:`Bearer ${SUPABASE_ANON_KEY}`,apikey:SUPABASE_ANON_KEY,"x-upsert":"false"},metadata:{bucketName:"media",objectName:path,contentType:selectedFile.type||"application/octet-stream",cacheControl:"3600"},onError:err=>{showError(errorBox,`Upload failed: ${err.message||err}`);reset()},onProgress:(sent,total)=>{const pct=Math.round(sent/total*100);progressBar.style.width=`${pct}%`;createBtn.textContent=`Uploading… ${pct}%`},onSuccess:async()=>{try{const{data:pub}=supabase.storage.from("media").getPublicUrl(path);const{error}=await supabase.from("rooms").insert({code,name:roomName,owner_token:ownerToken,media_url:pub.publicUrl,media_type:selectedFile.type.startsWith("video")?"video":"audio",media_name:selectedFile.name});if(error)throw error;rememberRoom(code,ownerToken);localStorage.setItem(`nightcast_host_${code}`,"1");window.location.href=`room.html?code=${code}`}catch(err){showError(errorBox,`Room creation failed: ${err.message||err}`);reset()}}});upload.findPreviousUploads().then(previous=>{if(previous.length)upload.resumeFromPreviousUpload(previous[0]);upload.start()})});
function reset(){createBtn.disabled=false;createBtn.textContent="Create room";progressWrap.style.display="none"}
codeInput.addEventListener("input",()=>{codeInput.value=codeInput.value.toUpperCase().replace(/[^A-Z0-9]/g,"")});joinBtn.addEventListener("click",async()=>{const code=codeInput.value.trim();if(code.length<4){showError(errorBox,"Enter a room code.");return}joinBtn.disabled=true;joinBtn.textContent="Checking…";const{data,error}=await supabase.from("rooms").select("code").eq("code",code).maybeSingle();joinBtn.disabled=false;joinBtn.textContent="Join room";if(error||!data){showError(errorBox,"No room found with that code.");return}window.location.href=`room.html?code=${code}`});codeInput.addEventListener("keydown",e=>{if(e.key==="Enter")joinBtn.click()});
async function loadOwnedRooms(){const owned=ownedRooms();if(!owned.length){roomsList.innerHTML='<div class="empty">Your rooms will appear here after you create one.</div>';return}const{data}=await supabase.from("rooms").select("code,name,media_type,created_at").in("code",owned.map(r=>r.code));const rows=data||[];roomsList.innerHTML=rows.length?rows.map(r=>`<div class="room-row"><div><strong>${escapeHtml(r.name)}</strong><span>${r.code} · ${r.media_type}</span></div><div class="row-actions"><a class="btn-ghost small" href="room.html?code=${r.code}">Open</a><button class="btn-ghost small danger" data-delete="${r.code}">Delete</button></div></div>`).join(""):'<div class="empty">No active rooms.</div>';roomsList.querySelectorAll("[data-delete]").forEach(btn=>btn.addEventListener("click",()=>deleteRoom(btn.dataset.delete)))}
async function deleteRoom(code){const entry=ownedRooms().find(r=>r.code===code);if(!entry)return;if(!confirm(`Delete room ${code}?`))return;const res=await fetch(`${SUPABASE_URL}/rest/v1/rooms?code=eq.${encodeURIComponent(code)}`,{method:"DELETE",headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,"x-nightcast-owner-token":entry.ownerToken,Prefer:"return=minimal"}});if(!res.ok){showError(errorBox,"Couldn't delete the room. You must be the room owner.");return}forgetRoom(code);loadOwnedRooms()}
function escapeHtml(v){return String(v).replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
loadOwnedRooms();
